#!/bin/bash

# Unzip to One - Unzips a PEDS collection of Xml files and combines
#                them into one uniquely-named Xml file.
#
# Copyright © 2020 David Yockey
#
# XSLT_PEDS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# XSLT_PEDS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with XSLT_PEDS.  If not, see <https://www.gnu.org/licenses/>.


# If no zip file if given, try and use the latest zip file in the current directory
# - Based on info from http://mywiki.wooledge.org/BashFAQ/003
if [ -z "$1" ]
	then
		for file in ./*.zip
			do
				[[ $file -nt $latest ]] && latest=$file
			done
		zipfile=$latest
	else
		zipfile=$1
fi

if [ ! -f "$zipfile" ]
	then
		errmsg="No zip file found.\nPlease make sure a zip file is located in your XSLT_PEDS folder\nor provide a zip file name on the command line."
		if [ -e "/usr/bin/zenity" ]
			then
				zenity --error --title="unzipo" --window-icon='error' --text="$errmsg" --no-wrap
			else
				echo "$errmsg"
		fi
		exit 1
fi

# Make a uniquely-named directory and move the zip file into it
datestamp=$(date +%Y%m%d-%H%M%S)
newdir="pairbulk-$datestamp"
mkdir $newdir

# Create an empty file with a unique datestamped name for the final combined Xml file
newfile="$newdir.xml"
touch $newfile

# Decompress zip file into $newdir
unzip -qq -d $newdir $zipfile

# Combine all Xml files from zip file into a single Xml file
firstfile=1
for file in $newdir/*.xml
	do
		[ -e "$file" ] || continue
		
		if [ "$firstfile" -eq 1 ]
			then
				# For the first file...
			
				bfile=$(basename "$file")
		
				## Insert Xslt linkage - Based on answer at https://stackoverflow.com/a/6541653/8100489
				awk -v ln=2 -v xsltln='<?xml-stylesheet type="text/xsl" href="peds.xsl"?>' 'NR == ln {print xsltln} {print}' "$file" > "/tmp/$bfile"
		
				## Intentionally OVERWRITE original Xml file with awked Xml file including Xslt linkage
				mv "/tmp/$bfile" "$file"
				
				firstfile=0
			else
			    # For the second and each subsequent file...
			    # (-i option requires GNU sed)
			
				## Split line 2 to separate the first uspat:PatentData tag from the opening uspat:PatentBulkData tag
				sed -i "2s/></>\n</" "$file"
				
				## Delete the XML header line and the opening uspat:PatentBulkData tag
				sed -i '1,2d' "$file"				
		fi
		
		# Delete the closing uspat:PatentBulkData tag from each file
		# (-i option requires GNU sed)
		sed -i '$d' "$file"
		
		# Append the current file to the new combined file
		cat "$file" >> $newfile
	done

# Finish the new combined file by appending a closing uspat:PatentBulkData tag
echo "</uspat:PatentBulkData>" >> $newfile

# TODO - Add item indices preceeding pat:InventionTitle content
#        as reassurance that data for all documents are displayed.
#        Use awk for this?

# Cleanup
rm -rf $newdir
if [ ! -d ./zipTrash ]
	then
		mkdir zipTrash
fi
mv $zipfile ./zipTrash

if [ -e "/usr/bin/zenity" ]
	then
		zenity --notification --timeout=5 --window-icon='info' --text="unzipo done!"
fi
