#!/bin/bash

# Unzip to Folder - Unzips a PEDS collection of Xml files to a folder
#                   while insuring that the folder is uniquely named.
#
# Copyright © 2020 David Yockey
#
# XSLT_PEDS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# XSLT_PEDS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with XSLT_PEDS.  If not, see <https://www.gnu.org/licenses/>.


# If no zip file if given, try and use the latest zip file in the current directory
# - Based on info from http://mywiki.wooledge.org/BashFAQ/003
if [ -z "$1" ]
	then
		for file in ./*.zip
			do
				[[ $file -nt $latest ]] && latest=$file
			done
		zipfile=$latest
	else
		zipfile=$1
fi

if [ ! -f "$zipfile" ]
	then
		errmsg="No zip file found.\nPlease make sure a zip file is located in your XSLT_PEDS folder\nor provide a zip file name on the command line."
		if [ -e "/usr/bin/zenity" ]
			then
				zenity --error --title="unzipf" --window-icon='error' --text="$errmsg" --no-wrap
			else
				echo "$errmsg"
		fi
		exit 1
fi

# Make a uniquely-named directory and move the zip file into it
datestamp=$(date +%Y%m%d-%H%M%S)
newdir="pairbulk-$datestamp"
mkdir $newdir

# Decompress zip file into $newdir
unzip -qq -d $newdir $zipfile

# Translate Xml files to Html files based on XSLT file peds.xsl,
# where the Html files are located in the uniquely-named directory
for file in $newdir/*.xml
	do
		[ -e "$file" ] || continue
		
		# Generate name for new html file - Based on answer https://stackoverflow.com/a/1224786/8100489
		htmlname="$newdir/$(basename -s .xml "$file").peds.htm"
		
		# Generate Html file from Xml file
		Xalan -o "$htmlname" "$file" "peds.xsl"
		
		rm -f "$file"
	done

# Cleanup
if [ ! -d ./zipTrash ]
	then
		mkdir zipTrash
fi
mv $zipfile ./zipTrash

if [ -e "/usr/bin/zenity" ]
	then
		zenity --notification --timeout=5 --window-icon='info' --text="unzipf done!"
fi
